// Vendors the OCS tools manifest from the site repo into ./data/ for the Cloudflare Workers
// ASSETS binding.  Re-run after any change to repo/tools/data/tools-manifest.json.
// Also stamps the OCG Standard §17 kernel_digest into worker.mjs (KERNEL_DIGEST const) —
// a content digest of worker.mjs itself, computed with the KERNEL_DIGEST line's own value
// blanked to a literal 'PLACEHOLDER' so the digest is stable/self-referential. Idempotent:
// running this twice yields the same digest and no further diff.
// Usage:  node generate.mjs
import { readFileSync, writeFileSync, mkdirSync, readdirSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { sourceDigest } from './lib/_buildid.mjs';

const ROOT = dirname(fileURLToPath(import.meta.url));
const REPO = resolve(ROOT, '..', 'repo');
const DATA = resolve(ROOT, 'data');

mkdirSync(DATA, { recursive: true });

writeFileSync(
  resolve(DATA, 'tools-manifest.json'),
  readFileSync(resolve(REPO, 'tools', 'data', 'tools-manifest.json'))
);

console.log('Vendored tools-manifest.json into ./data/');

// ---------------------------------------------------------------------------
// OCG Standard §17 — stamp KERNEL_DIGEST into worker.mjs.
// ---------------------------------------------------------------------------
const WORKER_PATH = resolve(ROOT, 'worker.mjs');
const KERNEL_DIGEST_RE = /^const KERNEL_DIGEST = 'sha256:(?:[0-9a-f]{64}|PLACEHOLDER)';$/m;

const workerSrc = readFileSync(WORKER_PATH, 'utf8');
if (!KERNEL_DIGEST_RE.test(workerSrc)) {
  throw new Error('generate.mjs: KERNEL_DIGEST line not found in worker.mjs (§17 stamp aborted).');
}

// Blank the KERNEL_DIGEST line's value to the literal 'PLACEHOLDER' so the digest is
// self-referential/stable, LF-normalize (sourceDigest does this too, but be explicit),
// then compute the digest over that neutralized text.
const neutralized = workerSrc.replace(KERNEL_DIGEST_RE, "const KERNEL_DIGEST = 'sha256:PLACEHOLDER';");
const digest = await sourceDigest(neutralized);

const stamped = workerSrc.replace(KERNEL_DIGEST_RE, `const KERNEL_DIGEST = '${digest}';`);
writeFileSync(WORKER_PATH, stamped);

console.log(`Stamped §17 KERNEL_DIGEST into worker.mjs: ${digest}`);

// ---------------------------------------------------------------------------
// §18 — regenerate the ESM receipt wrapper(s) the worker imports, from each
// canonical .json in kernels/receipts/, so the two can never drift (idempotent).
// Loops over every kernels/receipts/*.computeproof.json so new kernels' receipts
// are picked up automatically without touching this script again.
// ---------------------------------------------------------------------------
const RECEIPTS_DIR = resolve(ROOT, 'kernels', 'receipts');
const receiptJsonFiles = readdirSync(RECEIPTS_DIR).filter((f) => f.endsWith('.computeproof.json'));

for (const jsonFile of receiptJsonFiles) {
  const id = jsonFile.replace('.computeproof.json', '');
  const RECEIPT_JSON = resolve(RECEIPTS_DIR, jsonFile);
  const RECEIPT_MJS  = resolve(RECEIPTS_DIR, `${id}.computeproof.mjs`);
  const receiptObj = JSON.parse(readFileSync(RECEIPT_JSON, 'utf8'));
  writeFileSync(RECEIPT_MJS,
    `// AUTO-DERIVED from ${id}.computeproof.json (the canonical §18 receipt).\n` +
    '// Worker imports this ESM wrapper (portable across Node + Cloudflare/esbuild without a\n' +
    '// JSON import assertion). Regenerated by generate.mjs; do not hand-edit.\n' +
    'export default ' + JSON.stringify(receiptObj, null, 2) + ';\n');
  console.log(`Regenerated §18 receipt wrapper: ${id}.computeproof.mjs`);
}
